#FROM mcr.microsoft.com/windows/servercore:ltsc2022
FROM node

WORKDIR /usr/src/his_connect

COPY package.json ./
COPY CHANGELOG.md ./
RUN npm install && npm cache clean --force \
    && npm audit fix --force \
    && npm install -g pm2 nodemon typescript ts-node

RUN mkdir -p ./app
COPY app/. ./app

EXPOSE 3004
